name: "RDA_UNet_simple_v1"
model: "MaskedUNet"
task: "RDA"
masking_strategy_parameters:
    road_width_pixels: 40
train_location_strategy: "grid"
train_location_parameters:
  sample_generator_process_pool_size: 6
  adjustment_buffer_distance_px: 326
train_presentation_strategy: "weighted"
train_presentation_strategy_parameters:
  length: 4000
  expected_class_balances:
    Not Able To Determine: 1
    Partial Flooding: 1
    Partial Obstruction: 1
    Partial Road Condition: 1
    Particulate Partial: 1
    Particulate Total: 1
    Road Line: 1
    Total Destruction: 1
    Total Flooding: 1
    Total Obstruction: 1
  balance_monitor: "pixel"
train_dataset_adaptor_parameters:
  tile_x: 2048
  tile_y: 2048
  mask_x: 2048
  mask_y: 2048
  backend: "auto"
train_annotator_parameters:
  generate_adjusted_samples: True
validation_location_strategy: "grid"
validation_location_parameters:
  sample_generator_process_pool_size: 6
  adjustment_buffer_distance_px: 326
validation_presentation_strategy: "indexed"
validation_dataset_adaptor_parameters:
  tile_x: 2048
  tile_y: 2048
  mask_x: 2048
  mask_y: 2048
  backend: "auto"
validation_annotator_parameters:
  generate_adjusted_samples: True
channel_maps:
  background_class_idx: 0
  default_label: Road Line
  input_dataset_class_2_idx_map:
    Background: 0
    Not Able To Determine: 3
    Partial Flooding: 2
    Partial Obstruction: 2
    Partial Road Condition: 2
    Particulate Partial: 2
    Particulate Total: 3
    Road Line: 1
    Total Destruction: 3
    Total Flooding: 3
    Total Obstruction: 3
  model_class_2_color_map:
    Background:
      alpha: 0
      blue: 0
      green: 0
      red: 0
    Partial:
      alpha: 255
      blue: 0
      green: 255
      red: 255
    Road Line:
      alpha: 255
      blue: 0
      green: 255
      red: 0
    Total:
      alpha: 255
      blue: 0
      green: 0
      red: 255
  output_class_2_idx_map:
    Background: 0
    Partial: 2
    Road Line: 1
    Total: 3
input:
  road_line_buffer_width_pixels: 40
  road_line_segment_length_pixels: 40
  channels:
    blue: 2
    green: 1
    mask: 3
    red: 0
  sample_generator_parameters:
    label_tolerance: 0.1
  normalized_inputs: true
  validation_parameters:
    batch_size: 1
    validation_monitor: "val_macro_iou"
    validation_monitor_mode: "max"
    validation_checkpoint_save_top_k: 3
    validation_reduce_lr_on_plateau_patience: 3
    validation_reduce_lr_on_plateau_cooldown: 3
  training_parameters:
    gradient_clip_val: 10.0
    batch_size: 1
    grad_accumulation: 8
    l1_reg: 1.0e-06
    l2_reg: 1.0e-05
    log_images_every_n_steps: 100
    mask_x: 2048
    mask_y: 2048
    max_epochs: 100
    optimizer_parameters:
      name: "AdamW"
      lr: 0.0005
      weight_decay: 0.00001
    output_class_weights_strategy: "ipw"
    normalize_weights: False
    output_class_weights:
      Background: 1.0e-06
      Partial: 45
      Road Line: 1
      Total: 35
    samples_per_epoch: 4000
    tile_x: 2048
    tile_y: 2048
    loss_parameters:
      loss: [["cross entropy", 1.0]]
      gamma: 2
      alpha: 0.25
      bins: 10
      momentum: 0.9
      smooth: 1.0e-06
  model_parameters:
    layers:
      inc:
        out_channels: 32
        dilation: 1
        kernel_size: 5
        padding_mode: "zeros"
      down_1:
        in_channels: 32
        out_channels: 64
        dilation: 1
        kernel_size: 5
        padding_mode: "zeros"
      down_2:
        in_channels: 64
        out_channels: 128
        dilation: 1
        kernel_size: 5
        padding_mode: "zeros"
      down_3:
        in_channels: 128
        out_channels: 256
        dilation: 1
        kernel_size: 5
        padding_mode: "zeros"
      down_4:
        in_channels: 256
        out_channels: 512
        dilation: 1
        kernel_size: 5
        padding_mode: "zeros"
      down_5:
        in_channels: 512
        out_channels: 1024
        dilation: 1
        kernel_size: 5
        padding_mode: "zeros"
      up_0:
        attention: True
        bilinear: False
        in_channels: 1024
        out_channels: 512
      up_1:
        attention: True
        bilinear: False
        in_channels: 512
        out_channels: 256
      up_2:
        attention: True
        bilinear: False
        in_channels: 256
        out_channels: 128
      up_3:
        attention: True
        bilinear: False
        in_channels: 128
        out_channels: 64
      up_4:
        attention: True
        bilinear: False
        in_channels: 64
        out_channels: 32
