---
 name: "RandomBaseline_v1"
 model: "RandomBaseline"
 task: "RDA"
 channel_maps:
  default_label: "None"
  input_dataset_class_2_idx_map:
    Background: 0
    Not Able To Determine: 3
    Partial Flooding: 2
    Partial Obstruction: 2
    Partial Road Condition: 2
    Particulate Partial: 2
    Particulate Total: 3
    Road Line: 1
    Total Destruction: 3
    Total Flooding: 3
    Total Obstruction: 3
  output_class_2_idx_map:
    Background: 0
    Partial: 2
    Road Line: 1
    Total: 3
  model_class_2_color_map:
    Background:
      alpha: 0
      blue: 0
      green: 0
      red: 0
    Partial:
      alpha: 255
      blue: 0
      green: 255
      red: 255
    Road Line:
      alpha: 255
      blue: 0
      green: 255
      red: 0
    Total:
      alpha: 255
      blue: 0
      green: 0
      red: 255
  background_class_idx: 0
 optimizer_parameters:
  learning_rate: 0.0005
 input:
  channels:
    red: 0
    green: 1
    blue: 2
    mask: 3
  road_line_buffer_width_pixels: 40
  road_line_segment_length_pixels: 40
  training_parameters:
   output_class_weights:
    Background: 1.0e-06
    Partial: 45
    Road Line: 1
    Total: 35
   tile_x: 2048
   tile_y: 2048
   mask_x: 2048
   mask_y: 2048
  class_weights:
    Background: 1.0
    Partial: 1.0
    Road Line: 1.0
    Total: 1.0