name: "BDA_SegmenterVit_NoPreTrain_CCE_full"
model: "SegmenterVit"
task: "RDA"
masking_strategy_parameters:
    road_width_pixels: 40
train_location_strategy: "grid"
train_location_parameters:
  sample_generator_process_pool_size: 6
  adjustment_buffer_distance_px: 326
train_presentation_strategy: "weighted"
train_presentation_strategy_parameters:
  length: 4000
  expected_class_balances:
    Not Able To Determine: 1
    Partial Flooding: 1
    Partial Obstruction: 1
    Partial Road Condition: 1
    Particulate Partial: 1
    Particulate Total: 1
    Road Line: 1
    Total Destruction: 1
    Total Flooding: 1
    Total Obstruction: 1
  balance_monitor: "pixel"
train_dataset_adaptor_parameters:
  tile_x: 1024
  tile_y: 1024
  mask_x: 1024
  mask_y: 1024
  backend: "auto"
train_annotator_parameters:
  generate_adjusted_samples: True
validation_location_strategy: "grid"
validation_location_parameters:
  sample_generator_process_pool_size: 6
  adjustment_buffer_distance_px: 326
validation_presentation_strategy: "indexed"
validation_dataset_adaptor_parameters:
  tile_x: 1024
  tile_y: 1024
  mask_x: 1024
  mask_y: 1024
  backend: "auto"
validation_annotator_parameters:
  generate_adjusted_samples: True
channel_maps:
  background_class_idx: 0
  default_label: Road Line
  input_dataset_class_2_idx_map:
    Background: 0
    Not Able To Determine: 2
    Partial Flooding: 4
    Partial Obstruction: 3
    Partial Road Condition: 5
    Particulate Partial: 6
    Particulate Total: 10
    Road Line: 1
    Total Destruction: 9
    Total Flooding: 8
    Total Obstruction: 7
  model_class_2_color_map:
    Background:
      alpha: 0
      blue: 0
      green: 0
      red: 0
    Not Able To Determine:
      alpha: 255
      blue: 127
      green: 127
      red: 127
    Partial Flooding:
      alpha: 255
      blue: 255
      green: 255
      red: 0
    Partial Obstruction:
      alpha: 255
      blue: 255
      green: 0
      red: 255
    Partial Road Condition:
      alpha: 255
      blue: 0
      green: 255
      red: 255
    Particulate Partial:
      alpha: 255
      blue: 0
      green: 102
      red: 255
    Particulate Total:
      alpha: 255
      blue: 51
      green: 75
      red: 255
    Road Line:
      alpha: 255
      blue: 0
      green: 255
      red: 0
    Total Destruction:
      alpha: 255
      blue: 0
      green: 0
      red: 255
    Total Flooding:
      alpha: 255
      blue: 255
      green: 0
      red: 0
    Total Obstruction:
      alpha: 255
      blue: 255
      green: 0
      red: 127
  output_class_2_idx_map:
    Background: 0
    Not Able To Determine: 2
    Partial Flooding: 4
    Partial Obstruction: 3
    Partial Road Condition: 5
    Particulate Partial: 6
    Particulate Total: 10
    Road Line: 1
    Total Destruction: 9
    Total Flooding: 8
    Total Obstruction: 7
input:
  channels:
    blue: 2
    green: 1
    mask: 3
    red: 0
  normalized_inputs: true
  mask_input: false
  sample_generator_parameters:
    label_tolerance: 0.1
  road_line_buffer_width_pixels: 40
  road_line_segment_length_pixels: 40
  normalized_inputs: true
  validation_parameters:
    batch_size: 1
    validation_monitor: "val_macro_iou"
    validation_monitor_mode: "max"
    validation_checkpoint_save_top_k: 3
    validation_reduce_lr_on_plateau_patience: 3
    validation_reduce_lr_on_plateau_cooldown: 3
  training_parameters:
    gradient_clip_val: 10.0
    alpha: 0.25
    batch_size: 1
    gamma: 2
    grad_accumulation: 8
    l1_reg: 1.0e-06
    l2_reg: 1.0e-05
    log_images_every_n_steps: 100
    output_class_weights_strategy: "ipw"
    normalize_weights: False
    mask_x: 1024
    mask_y: 1024
    max_epochs: 100
    optimizer_parameters:
      name: "AdamW"
      lr: 0.0005
      weight_decay: 0.00001
    output_class_weights:
      Background: 1.0e-06
      Not Able To Determine: 45
      Partial Flooding: 45
      Partial Obstruction: 45
      Partial Road Condition: 45
      Particulate Partial: 45
      Particulate Total: 35
      Road Line: 1
      Total Destruction: 35
      Total Flooding: 35
      Total Obstruction: 35
    samples_per_epoch: 4000
    tile_x: 1024
    tile_y: 1024
    loss_parameters:
      loss: [["cross entropy", 1.0]]
      gamma: 2
      alpha: 0.25
      bins: 10
      momentum: 0.9
      smooth: 1.0e-06
  validation_parameters:
    batch_size: 1
    validation_monitor: "val_macro_iou"
    validation_monitor_mode: "max"
    validation_checkpoint_save_top_k: 3
    validation_reduce_lr_on_plateau_cooldown: 3
    validation_reduce_lr_on_plateau_patience: 3
  model_parameters:
    decoder_parameters:
      in_channels: 1024
      channels: 1024
      num_layers: 2
      num_heads: 16
      embed_dims: 1024
      dropout_ratio: 0.1
      align_corners: False
      out_indicies: [2,9,16,23]
    n_cls: 11
    normalization: "vit"
    encoder_parameters:
      backbone: "scalemae"
      backbone_parameters:
      normalization: "vit"
      vit_model: vit_large_patch16
      n_heads: 16
      n_layers: 24
      patch_size: 16
      drop_path_rate: 0.1
      dropout: 0.0
      global_pool: False
      